study:
  study_name: "test"
  direction: "minimize"
  storage: "sqlite:///optuna.db"

dataloader:
  batch_size: 64
  data_path: /home/luke-padmore/Source/flow-matching-mnist/data
  num_workers: 4
  shuffle: true
  transform: "default"

unet:
  fixed:
    max_time_period: 1000.0
  choices:
    channels:
      type: categorical
      choices:
        - [1, 64, 128]
        - [1, 64, 128, 256]
    d_time:
      type: categorical
      choices: [64, 128, 256]
    activation:
      type: categorical
      choices: [silu, relu, gelu]
    upsample_mode:
      type: categorical
      choices: [nearest, bilinear, convtranspose]

optim:
  fixed:
    name: adamw
  choices:
    lr:
      type: float
      low: 1e-5
      high: 5e-4
      log: true
    weight_decay:
      type: float
      low: 1e-6
      high: 1e-2
      log: true